services:
  # Development Joossam FastAPI Application
  app:
    build:
      context: ../../services/fastapi
      dockerfile: ../../deploy/docker/Dockerfile.dev
    container_name: joossam-app-dev
    restart: unless-stopped
    labels:
      kompose.namespace: joossam
    ports:
      - 8001:8000
    environment:
      - ENV=development
    networks:
      - joossam-network
    volumes:
      - ../../services/fastapi:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  joossam-network:
    driver: bridge
    name: joossam-network-dev

