apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joossam-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitea0213.kro.kr/bluemayne/joossam.git
    targetRevision: develop
    path: deploy/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: joossam-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
