apiVersion: apps/v1
kind: Deployment
metadata:
  name: joossam-app
  labels:
    environment: production
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: joossam-app
          resources:
            requests:
              memory: "80Mi"
              cpu: "25m"
            limits:
              memory: "200Mi"
