apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam

resources:
  - ../../base
  - resourcequota.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: main-sha-ca8e4ae8bf34c5d65a0c968de331b15d8dad060e

patchesStrategicMerge:
  - deployment-patch.yaml
