apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam

resources:
  - ../../base
  - resourcequota.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: main-sha-206989c78299bf8983b327da5ee8eefb06ec9429

patchesStrategicMerge:
  - deployment-patch.yaml
