apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: main-sha-d5eb504bc54c9aa9de7e68287bf90096172ebc96

patchesStrategicMerge:
  - deployment-patch.yaml
