apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: main-sha-6610d7da42e34a790aaf8765b152a4d1a698e4e0

patchesStrategicMerge:
  - deployment-patch.yaml
