apiVersion: v1
kind: ResourceQuota
metadata:
  name: joossam-quota
  namespace: joossam
spec:
  hard:
    requests.memory: "1536Mi"
    requests.cpu: "900m"
    limits.memory: "2304Mi"
    limits.cpu: "2100m"
    pods: "9"
