apiVersion: v1
kind: ResourceQuota
metadata:
  name: joossam-quota
  namespace: joossam
spec:
  hard:
    requests.memory: "300Mi"
    requests.cpu: "200m"
    limits.memory: "400Mi"
    limits.cpu: "400m"
    pods: "3"
