apiVersion: v1
kind: ResourceQuota
metadata:
  name: joossam-quota
  namespace: joossam
spec:
  hard:
    requests.memory: "512Mi"
    requests.cpu: "300m"
    limits.memory: "768Mi"
    limits.cpu: "700m"
    pods: "3"
