apiVersion: apps/v1
kind: Deployment
metadata:
  name: joossam-app
  labels:
    environment: development
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: joossam-app
          resources:
            requests:
              memory: "179Mi"
              cpu: "70m"
            limits:
              memory: "358Mi"
              cpu: "350m"
