apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: develop-sha-535871eb4091fc1886999e67a0c553f4c3591119

patchesStrategicMerge:
  - deployment-patch.yaml
