apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: develop-sha-5b3f226c0b17d441f014496183a9950c3bb2435a

patchesStrategicMerge:
  - deployment-patch.yaml
