apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: develop-sha-d1c37b26dae0ee6a01ffa3b2edd1f34a67bb25e1

patchesStrategicMerge:
  - deployment-patch.yaml
