apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/joossam
    newTag: develop-sha-3867ab70aaad59bfae294fa125c247e6b5c3f34e

patchesStrategicMerge:
  - deployment-patch.yaml
