apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: develop-sha-f47f2a0f48f62da306008256b9c967f55733804e

patchesStrategicMerge:
  - deployment-patch.yaml
