apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정 (dev 브랜치 사용 시)
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: main-sha-227fdc85f227ae0af1a6a7ed53e45bdda50a8517

patchesStrategicMerge:
  - deployment-patch.yaml
