apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/joossam
    newTag: develop-sha-f10617531ed303a27db98716a4dfd860a716e85c

patchesStrategicMerge:
  - deployment-patch.yaml
