apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/joossam
    newTag: develop-sha-a9cd687fb81de8f0b632f520e089eb06d5465227

patchesStrategicMerge:
  - deployment-patch.yaml
