apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: github.com/Mayne0213/joossam
    newTag: develop-sha-b7825fd5fd672a5ab29535083e597318ba7895d0

patchesStrategicMerge:
  - deployment-patch.yaml
