apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/joossam
    newTag: develop-sha-e03cde560b87b092399956c4671dbae0a56058a5

patchesStrategicMerge:
  - deployment-patch.yaml
