apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joossam-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: gitea0213.kro.kr/bluemayne/joossam
    newTag: develop-sha-02c45c58af78b5d063b72312dcc553f67850c593

patchesStrategicMerge:
  - deployment-patch.yaml
