apiVersion: v1
kind: ResourceQuota
metadata:
  name: joossam-dev-quota
  namespace: joossam-dev
spec:
  hard:
    requests.memory: "200Mi"
    requests.cpu: "60m"
    limits.memory: "400Mi"
    limits.cpu: "150m"
    pods: "6"
